'use strict';
const assert = require('node:assert/strict');
const KC = require('./core.js');
const K = require('../tools/lib/engine.js');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const AT = Date.UTC(2026, 9, 1), BAR = 9e5;
const raw = (overrides = {}) => ({ id: 'B4', symbol: 'TEST', sym: 'TESTUSDT', t: AT, tf: '4h', dir: 'long', status: 'active', gates: [], plan: { bids: [100, 99, 98, 97].map((price, i) => ({ price, weight: [0.1, 0.2, 0.3, 0.4][i] })), stop: 95, tps: [{ price: 105 }, { price: 110 }, { price: 115 }] }, ...overrides });
const context = { at: AT, price: 101, source: 'binance-usdm', closedAt: AT };
const decision = (overrides, changes) => KC.qualify(raw(overrides), { ...context, ...changes });
const candle = (offset, o, h, l, c) => [AT + offset * BAR, o, h, l, c, 1];
const run = (d, rows) => KC.simulate(d, K.fromRows(rows), AT + rows.length * BAR);

const first = decision();
assert.equal(first.accepted, true);
assert.equal(first.plan.riskUsd, 100);
assert(first.plan.weightedNetR > 0);
assert(first.plan.tp1ThenStopR < 0, 'Costs prevent a TP1-then-stop guarantee');
assert(Object.isFrozen(first.raw.plan.bids));
assert.equal(decision({}, { settings: { account: 2000, riskPct: 1 } }).plan.riskUsd, 20);
assert.equal(decision({ id: 'C6', tf: '1h' }).accepted, true, 'Validity is checked before batch confluence qualification');
assert.equal(decision({ id: 'C6', tf: '12h' }).accepted, true);
assert.equal(decision({ id: 'A1' }).validPlan, true, 'Rejected valid plans remain evaluable');
for (const d of [decision({ status: 'forming' }), decision({ gates: ['HTF blocked'] }), decision({}, { price: 105 }), decision({}, { closedAt: AT - 2 * BAR }), decision({}, { closedAt: AT + 1 }), decision({}, { source: 'bybit' }), decision({}, { price: NaN }), decision({}, { settings: { riskPct: -1 } })]) assert.equal(d.accepted, false);
assert.equal(decision({ plan: { ...raw().plan, stop: 99.5 } }).validPlan, false);
assert.equal(decision({ plan: { ...raw().plan, tps: [{ price: 103 }, { price: 102 }] } }).validPlan, false);
assert.equal(decision({ plan: { ...raw().plan, tps: [{ price: 100 }] } }).validPlan, false);
assert.equal(decision({}, { settings: { feePct: 10 } }).validPlan, false);
assert.equal(decision({}, { settings: { account: 1e308, riskPct: 100 } }).validPlan, false);
assert.equal(KC.qualify(null, context).accepted, false);

const checked = KC.closedRows([candle(-2, 100, 101, 99, 100), candle(-1, 100, 101, 99, 100), candle(0, 100, 101, 99, 100), candle(-1, 100, 101, 99, 100), [AT - 3 * BAR, 100, 99, 101, 100, 1]], '15m', AT);
assert.equal(checked.rows.length, 2);
assert.equal(checked.closedAt, AT);
assert.equal(checked.invalid, 2);
assert.equal(checked.stale, false);
assert.equal(KC.closedRows([], '15m', AT).stale, true);
assert.equal(KC.closedRows([candle(-1, 100, 101, 99, 100)], '15m', AT + BAR).stale, true);

const grouped = KC.deduplicate([decision({ id: 'C3' }), first, { ...decision({ id: 'A1' }), accepted: false }]);
assert.equal(grouped.ideas.length, 1);
assert.equal(grouped.ideas[0].setupId, 'B4');
assert.equal(grouped.ideas[0].support.length, 2);
assert.equal(grouped.decisions.filter(x => x.accepted).length, 1);
assert.equal(grouped.decisions[0].duplicateOf, first.id);
assert.equal(KC.deduplicate([decision({ t: AT + BAR }, { at: AT + BAR, closedAt: AT + BAR })], grouped.ideas).ideas.length, 1);
assert.equal(KC.deduplicate([first, decision({ symbol: 'OTHER' })]).ideas.length, 2);
assert.deepEqual(KC.deduplicate([first, decision({ id: 'C3' })]).ideas, KC.deduplicate([decision({ id: 'C3' }), first]).ideas);

const original = KC.createEvent('signal', AT, first);
const changed = KC.createEvent('upgrade', AT + BAR, { originalId: original.id, grade: 'A' });
const ledger = KC.appendEvents([original], [original, changed]);
assert.equal(ledger.length, 2);
assert.equal(ledger[0].payload.t, AT);
assert.throws(() => KC.appendEvents(ledger, [{ ...original, payload: {} }]), /cannot be rewritten/);
assert(Object.isFrozen(ledger[0].payload));

const stopped = run(first, [candle(0, 101, 106, 94, 100)]);
assert.equal(stopped.st, 'closed');
assert.equal(stopped.reason, 'stop');
assert(stopped.R < -0.99 && stopped.R > -1.01);
assert.equal(stopped.tp[0], false);
const filledAndTarget = run(first, [candle(0, 101, 106, 99.5, 105)]);
assert.equal(filledAndTarget.st, 'open');
assert.equal(filledAndTarget.tp[0], false);
assert.equal(filledAndTarget.amb, 1);
assert(Math.abs(filledAndTarget.fill - 0.1) < 1e-12);
const partial = run(first, [candle(0, 101, 102, 99.5, 100), candle(1, 100, 106, 99.5, 105), candle(2, 105, 105, 94, 95)]);
assert.equal(partial.st, 'closed');
assert.equal(partial.tp[0], true);
assert(Math.abs(partial.tp1Fraction - 0.5) < 1e-12, 'TP1 amount uses actual partial-fill average, not full-ladder average');
assert(partial.R < 0);
assert.equal(partial.fills.length, 1);
const profit = run(first, [candle(0, 101, 102, 96.5, 100), candle(1, 100, 116, 99, 115)]);
assert.equal(profit.st, 'closed');
assert(profit.R > 0);
assert.deepEqual(profit.tp, [true, true, true]);
const rejected = { ...decision({ id: 'D5' }), accepted: false };
assert.equal(run(rejected, [candle(0, 101, 102, 96.5, 100), candle(1, 100, 116, 99, 115)]).R, profit.R);
assert.equal(run(first, [candle(0, 101, 106, 100.5, 105)]).st, 'missed');
const gap = KC.simulate(first, K.fromRows([candle(1, 101, 102, 99, 100)]), AT + 2 * BAR);
assert.equal(gap.coverageComplete, false);
assert.equal(gap.dataMissing, true);
assert.equal(gap.fill, 0, 'Missing candles cannot fabricate a later fill');
const immediate = decision({}, { price: 99.5 });
assert.equal(immediate.plan.units, first.plan.units, 'Improved decision quote cannot increase delayed-entry size');
const now = KC.simulate(immediate, K.fromRows([]), AT);
assert.equal(now.st, 'pending');
assert.equal(now.avgFill, null);
assert.equal(now.coverageComplete, true);
assert.equal(KC.simulate(first, K.fromRows([]), AT + BAR).coverageComplete, false);
const midBarAt = AT + 60000;
const midBar = decision({ t: midBarAt }, { at: midBarAt });
const noPastWick = KC.simulate(midBar, K.fromRows([candle(0, 101, 106, 94, 101), candle(1, 101, 102, 100.5, 101)]), AT + 2 * BAR);
assert.equal(noPastWick.fill, 0, 'A pre-emission wick cannot fill a newly emitted signal');
assert.equal(noPastWick.st, 'pending');
assert.equal(noPastWick.coverageComplete, true);
assert.equal(noPastWick.partialBarSkippedMs, BAR - 60000);
assert.equal(noPastWick.activationAt, AT + BAR);
assert.equal(KC.simulate(midBar, K.fromRows([]), AT + BAR).coverageComplete, true, 'No complete post-emission bar is due yet');
const delayedFill = KC.simulate(midBar, K.fromRows([candle(1, 99.5, 100, 99.1, 99.5)]), AT + 2 * BAR);
assert.equal(delayedFill.st, 'open');
assert.equal(delayedFill.tFill, AT + BAR);
assert.equal(delayedFill.avgFill, 99.5);
const expire = decision({ tf: '15m' });
assert.equal(run(expire, Array.from({ length: 20 }, (_, i) => candle(i, 101, 102, 100.5, 101))).st, 'expired');
const timeClose = decision({ tf: '15m' }, { price: 99.5 });
assert.equal(run(timeClose, Array.from({ length: 100 }, (_, i) => candle(i, 99.5, 100, 99.1, 99.5))).reason, 'time');

const short = decision({ dir: 'short', plan: { bids: [102, 103, 104, 105].map((price, i) => ({ price, weight: KC.POLICY.entryWeights[i] })), stop: 107, tps: [{ price: 97 }, { price: 92 }, { price: 87 }] } });
assert.equal(short.accepted, true);
const shortStop = run(short, [candle(0, 101, 108, 90, 100)]);
assert.equal(shortStop.reason, 'stop');
assert(shortStop.R < 0);
assert.equal(shortStop.tp[0], false);
const summary = KC.summarize([{ ...first, ev: stopped }, { ...rejected, ev: profit }, { ...immediate, ev: delayedFill }]);
assert.equal(summary.total.closedN, 2);
assert.equal(summary.total.openN, 1);
assert.equal(summary.accepted.closedN, 1);
assert.equal(summary.rejected.closedN, 1);
assert.equal(summary.groups.length, 2);
assert.equal(summary.total.netR, stopped.R + profit.R);
assert.equal(summary.total.drawdownR, -stopped.R);
const browser = { window: {} };
vm.createContext(browser);
vm.runInContext(fs.readFileSync(path.join(__dirname, '../tools/lib/engine.js'), 'utf8'), browser);
vm.runInContext(fs.readFileSync(path.join(__dirname, 'confluence-data.js'), 'utf8'), browser);
vm.runInContext(fs.readFileSync(path.join(__dirname, 'core.js'), 'utf8'), browser);
assert.equal(browser.window.KC.POLICY.version, KC.POLICY.version);
assert.equal(browser.window.KC.qualify(raw(), context).accepted, true, 'The browser and Node exports use the same policy');
console.log('Krillin Chatgpt core: all offline assertions passed');
