'use strict';
const assert = require('node:assert/strict');
const KM = require('./market.js');
const K = require('../tools/lib/engine.js');
const C = require('./core.js');
const DAY = 86400000, STEP = 900000;
const AT = Date.parse('2026-10-01T12:00:00Z');
const meta = (symbol, extra = {}) => Object.assign({ symbol, quoteAsset: 'USDT', marginAsset: 'USDT', status: 'TRADING', contractType: 'PERPETUAL', underlyingType: 'COIN', underlyingSubType: [], onboardDate: AT - 2000 * DAY }, extra);
const response = (value, status = 200, headers = {}) => ({ ok: status >= 200 && status < 300, status, headers: { get: key => headers[key] === undefined ? null : headers[key] }, json: async () => value });
function row(t, ms, close = 100, volume = 1000) { return [t, String(close - 0.1), String(close + 1), String(close - 1), String(close), '10', t + ms - 1, String(volume), 1, '1', '100', '0']; }
function fake(options = {}) {
  const calls = []; let timeCalls = 0;
  const fetch = async url => {
    const u = new URL(url); calls.push(u);
    const liveAt = options.at ? options.at() : AT;
    if (u.pathname === '/fapi/v1/time') return response({ serverTime: options.advance && timeCalls++ ? liveAt + STEP : liveAt + 10000 });
    if (u.pathname === '/fapi/v1/exchangeInfo') return response({ symbols: [meta('BTCUSDT'), meta('ETHUSDT'), meta('PAXGUSDT'), meta('AAPLUSDT', { contractType: 'TRADIFI_PERPETUAL' }), meta('DEFIUSDT', { underlyingType: 'INDEX' }), meta('USDCUSDT'), meta('WBTCUSDT')], rateLimits: [] });
    if (u.pathname === '/fapi/v1/ticker/bookTicker') return response(['BTCUSDT', 'ETHUSDT'].map(symbol => ({ symbol, bidPrice: '104.95', askPrice: '105.05', time: options.staleQuote ? liveAt - 120000 : liveAt + 9500 })));
    assert.equal(u.pathname, '/fapi/v1/klines');
    const tf = u.searchParams.get('interval'), ms = KM.TF[tf];
    const at = Number(u.searchParams.get('endTime')) + 1;
    const limit = Number(u.searchParams.get('limit'));
    const hasStart = u.searchParams.has('startTime');
    const available = !hasStart && limit === 1000 && options.shortHistory ? 300 : limit;
    const first = hasStart ? Number(u.searchParams.get('startTime')) : Math.floor(at / ms) * ms - available * ms;
    const count = Math.min(limit, Math.floor((at - first) / ms));
    let rows = Array.from({ length: count }, (_, i) => row(first + i * ms, ms, 100 + i * 0.005, u.searchParams.get('symbol') === 'ETHUSDT' ? 2000 : 1000));
    if (options.gap && tf === '4h') rows.splice(10, 1);
    if (options.universeGap && tf === '1d' && limit === 8 && u.searchParams.get('symbol') === 'ETHUSDT') rows.pop();
    if (options.forming) rows.push(row(Math.floor(at / ms) * ms, ms, 9999));
    return response(rows);
  };
  return { fetch, calls };
}
async function main() {
  assert(KM.eligible(meta('BTCUSDT')));
  for (const symbol of ['PAXGUSDT', 'XAUTUSDT', 'USDCUSDT', '1000WBTCUSDT', 'QQQUSDT']) assert(!KM.eligible(meta(symbol)), symbol);
  assert(!KM.eligible(meta('ABCUSDT', { underlyingType: 'INDEX' })));
  assert(!KM.eligible(meta('ABCUSDT', { contractType: 'TRADIFI_PERPETUAL' })));
  assert(!KM.eligible(meta('ABCUSDT', { underlyingSubType: ['STOCK'] })));
  assert(!KM.eligible(meta('ABCUSDT', { underlyingType: undefined })));
  assert.equal(KM.baseOf('1000PEPEUSDT'), 'PEPE');
  assert.equal(KM.rowsOf([row(AT - STEP, STEP), row(AT, STEP, 999)], '15m', AT).length, 1);
  assert.throws(() => KM.rowsOf({ code: -1 }, '15m', AT), /invalid candle data/);
  assert.throws(() => KM.rowsOf([row(AT - STEP, STEP, -2)], '15m', AT), /Invalid Binance OHLC/);
  const badClose = row(AT - STEP, STEP); badClose[6] = AT;
  assert.throws(() => KM.rowsOf([badClose], '15m', AT), /Invalid Binance OHLC/);
  assert.throws(() => KM.complete([[AT - 3 * STEP], [AT - STEP]], '15m', AT), /Gap/);

  const api = fake({ forming: true });
  const client = KM.createClient({ fetch: api.fetch });
  const result = await client.scan({ universeSize: 2 });
  assert.equal(result.featureAt, AT);
  assert.equal(result.at, AT + 10000);
  assert.equal(result.source, 'binance-usdm');
  assert.equal(result.universe[0].sym, 'ETHUSDT');
  assert.equal(result.universe[0].quoteVolume, 2000);
  assert.equal(result.counts.analyzed, 2);
  assert.equal(result.counts.scanned, 2);
  assert.equal(result.errors.length, 0);
  assert(result.rawSignals.length > 0, 'Engine should detect research setups on deterministic candles');
  for (const s of result.rawSignals) {
    assert.equal(s.t, AT + 10000, 'Signals must not be backdated to the feature boundary');
    assert.equal(s.symbol, s.base);
    assert.equal(s.px, s.dir === 'short' ? 104.95 : 105.05);
    assert(s.scanPrice < 200, 'Forming candle must not drive indicators or scan price');
    assert.equal(s.marketData.closedAt, AT);
    assert.equal(s.marketData.valid, true);
    assert.equal(s.marketData.history['15m'], 1000);
    assert.equal(C.qualify(s, { at: result.at, price: s.px, source: result.source, closedAt: s.marketData.closedAt, valid: s.marketData.valid }).dataValid, true, 'Market payload must match the decision-layer contract');
  }
  const volume = api.calls.filter(u => u.pathname === '/fapi/v1/klines' && u.searchParams.get('limit') === '8');
  assert.equal(volume.length, 2, 'Excluded contracts must not enter volume ranking');
  assert(volume.every(u => Number(u.searchParams.get('endTime')) === Math.floor(AT / DAY) * DAY - 1));
  assert(!api.calls.some(u => /24hr|coingecko|bybit/.test(u.href)));
  const before = api.calls.filter(u => u.pathname === '/fapi/v1/klines').length;
  await client.scan({ universeSize: 2 });
  assert.equal(api.calls.filter(u => u.pathname === '/fapi/v1/klines').length, before, 'Same-boundary scans should reuse validated history');
  const recent = await client.candles('BTCUSDT', '15m', { at: result.at, startTime: AT - 5 * STEP + 1000 });
  assert.equal(recent.t.length, 4);
  assert.equal(api.calls.filter(u => u.pathname === '/fapi/v1/klines').length, before, 'Recent paper evaluation must reuse validated scan candles');
  const short = await KM.createClient({ fetch: fake({ shortHistory: true }).fetch }).scan({ universeSize: 2 });
  assert.equal(short.counts.scanned, 2, 'Shorter daily history must not crash derived weekly context');
  assert.equal(short.coinData[0].history['1d'], 300);
  assert(short.btcContext.bias['1w']);
  let featureClock = AT, localClock = AT;
  const cachedApi = fake({ at: () => featureClock });
  const cached = KM.createClient({ fetch: cachedApi.fetch, now: () => localClock });
  await cached.scan({ universeSize: 2 });
  const cachedRequests = cachedApi.calls.filter(u => u.pathname === '/fapi/v1/klines').length;
  featureClock += STEP;
  await cached.scan({ universeSize: 2 });
  const incrementalRequests = cachedApi.calls.filter(u => u.pathname === '/fapi/v1/klines').slice(cachedRequests);
  assert.equal(incrementalRequests.length, 2, 'Only new 15m candles are needed after one boundary');
  assert(incrementalRequests.every(u => u.searchParams.get('startTime') === String(AT) && u.searchParams.get('limit') === '1'));
  const priorVolumeRequests = cachedApi.calls.filter(u => u.searchParams.get('limit') === '8').length;
  localClock += 3600001;
  await cached.scan({ universeSize: 2 });
  assert.equal(cachedApi.calls.filter(u => u.pathname === '/fapi/v1/exchangeInfo').length, 2);
  assert.equal(cachedApi.calls.filter(u => u.searchParams.get('limit') === '8').length, priorVolumeRequests, 'Unchanged hourly metadata must not repeat daily volume ranking');

  const forward = fake();
  const series = await KM.createClient({ fetch: forward.fetch }).candles('BTCUSDT', '15m', { at: AT, startTime: AT - 2005 * STEP });
  assert.equal(series.t.length, 2005);
  assert.equal(series.t[0], AT - 2005 * STEP);
  assert.equal(series.t.at(-1), AT - STEP);
  assert.equal(forward.calls.length, 3, 'Forward evaluation must paginate beyond the first thousand bars');
  const aligned = await KM.createClient({ fetch: fake().fetch }).candles('BTCUSDT', '15m', { at: AT, startTime: AT - 2 * STEP + 1 });
  assert.equal(aligned.t[0], AT - STEP, 'A partially elapsed candle must not be replayed after an actual alert');
  await assert.rejects(() => client.candles('BTCUSDT', '15m', { at: AT, startTime: AT - 50001 * STEP }), /50,000/);
  await assert.rejects(() => client.candles('BTCUSDT', '1w', { at: AT }), /Invalid Binance symbol/);
  await assert.rejects(() => KM.createClient({ fetch: fake({ universeGap: true }).fetch }).scan({ universeSize: 2 }), /ranking is incomplete/);
  await assert.rejects(() => KM.createClient({ fetch: fake({ gap: true }).fetch }).scan({ universeSize: 2 }), /BTC closed-candle context is incomplete/);
  await assert.rejects(() => KM.createClient({ fetch: fake({ advance: true }).fetch }).scan({ universeSize: 2 }), /new 15-minute candle/);
  const stale = await KM.createClient({ fetch: fake({ staleQuote: true }).fetch }).scan({ universeSize: 2 });
  assert(stale.rawSignals.length > 0, 'Raw detections must remain auditable after quote rejection');
  assert(stale.rawSignals.every(s => Array.isArray(s.chartLevels)), 'Each observation retains its setup reference snapshot');
  for (const s of stale.rawSignals) {
    const bounds = [...(s.entry || s.watchZone || []), s.stop, ...(s.plan && s.plan.tps || []).map(tp => tp.price)].filter(x => Number.isFinite(x) && x > 0);
    assert(s.chartLevels.every(lv => lv.hi >= Math.min(...bounds) && lv.lo <= Math.max(...bounds)), 'Reference levels overlap the setup range');
  }
  assert(stale.rawSignals.every(s => !s.marketData.valid && s.px === null));
  assert(stale.rawSignals.every(s => C.qualify(s, { at: stale.at, price: s.px, source: stale.source, closedAt: s.marketData.closedAt, valid: s.marketData.valid }).reasonCodes.includes('invalid_data')));
  assert.equal(stale.errors.length, 2);

  let clock = AT, requests = 0;
  const throttled = KM.createClient({ now: () => clock, fetch: async () => { requests++; return response({}, 429, { 'Retry-After': '2' }); } });
  await assert.rejects(() => throttled.serverTime(), e => e.retryAt === AT + 2000);
  await assert.rejects(() => throttled.serverTime(), /rate limit/);
  assert.equal(requests, 1, 'Requests must stay paused during Retry-After');
  clock += 2000;
  await assert.rejects(() => throttled.serverTime(), /HTTP 429/);
  assert.equal(requests, 2);
  await assert.rejects(() => KM.createClient({ fetch: async () => response({}, 451) }).serverTime(), /region or network/);
  await assert.rejects(() => KM.createClient({ fetch: async () => { throw new Error('Offline'); } }).serverTime(), e => e.fatal === true && /unreachable/.test(e.message));
  await assert.rejects(() => KM.createClient({ fetch: async () => response({ code: -1121, msg: 'Invalid symbol.' }) }).serverTime(), /-1121/);
  await assert.rejects(() => KM.createClient({ fetch: async () => response({ serverTime: -1 }) }).serverTime(), /Invalid Binance server/);
  await assert.rejects(() => client.scan({ universeSize: 0 }), /Invalid scan/);
  assert.equal(typeof K.analyzeCoin, 'function');
  console.log('market tests passed: closed candles, prior-day universe, immutable timing, executable quotes, pagination, and failure handling');
}
main().catch(e => { console.error(e); process.exitCode = 1; });
